name: CVE scan

on:
  schedule:
    - cron: '0 0 * * *'

jobs:

  cve-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run CVE scan
        run: 'mvn clean install -P CVE-Check -Dmaven.test.skip=true'

      - name: Archive CVE scan results
        uses: actions/upload-artifact@v2
        with:
          name: cve.results
          path: |
            target/dependency-check-report.html
